# TCL File Generated by Component Editor 15.0
# Fri Jul 13 10:58:45 GMT+08:00 2018
# DO NOT MODIFY


# 
# User_LTM_ADC "User_LTM_ADC" v1.0
#  2018.07.13.10:58:45
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module User_LTM_ADC
# 
set_module_property DESCRIPTION ""
set_module_property NAME User_LTM_ADC
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME User_LTM_ADC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adc_spi_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adc_spi_controller.v VERILOG PATH Uesr_Files/adc_spi_controller.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SYSCLK_FRQ INTEGER 50000000
set_parameter_property SYSCLK_FRQ DEFAULT_VALUE 50000000
set_parameter_property SYSCLK_FRQ DISPLAY_NAME SYSCLK_FRQ
set_parameter_property SYSCLK_FRQ TYPE INTEGER
set_parameter_property SYSCLK_FRQ UNITS None
set_parameter_property SYSCLK_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYSCLK_FRQ HDL_PARAMETER true
add_parameter ADC_DCLK_FRQ INTEGER 1000
set_parameter_property ADC_DCLK_FRQ DEFAULT_VALUE 1000
set_parameter_property ADC_DCLK_FRQ DISPLAY_NAME ADC_DCLK_FRQ
set_parameter_property ADC_DCLK_FRQ TYPE INTEGER
set_parameter_property ADC_DCLK_FRQ UNITS None
set_parameter_property ADC_DCLK_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADC_DCLK_FRQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
add_interface_port avalon_slave_0 avs_address address Input 4
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset clock_reset
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_iRST_n export_irst_n Input 1
add_interface_port conduit_end_0 coe_oADC_DIN export_oadc_din Output 1
add_interface_port conduit_end_0 coe_oADC_DCLK export_oadc_dclk Output 1
add_interface_port conduit_end_0 coe_oADC_CS export_oadc_cs Output 1
add_interface_port conduit_end_0 coe_iADC_DOUT export_iadc_dout Input 1
add_interface_port conduit_end_0 coe_iADC_BUSY export_iadc_busy Input 1
add_interface_port conduit_end_0 coe_iADC_PENIRQ_n export_iadc_penirq_n Input 1
add_interface_port conduit_end_0 coe_oTOUCH_IRQ export_otouch_irq Output 1

